### PR TITLE
changes setList to pieceList; adds example for new pieceList;

### PR DESCRIPTION
**Pull request by bkudler**
added an example on how to use different pieces in "set list". The name 'set list' was confusing for me because it seems like a combination of a set and a list, two data structures that SC already creates. Thought a name change made more sense.

### CODE REVIEW

**Comment by catniptwinz** [comment]
Makes sense. It was "inherited" from a pattern I use when writing code for live sets, hence "setList". I agree that it's not an idea variable name!

**Comment by bkudler** [comment]
cool. are you able to merge the request or is it not allowing you?

**Comment by catniptwinz** [comment]
We're good. Longer-term it occurs to me that ```~pieceList``` may not be ideal either, since it doesn't refer to the list of all available pieces. I'm after something like ```~playerPieces``` but better...

**Comment by bkudler** [comment]
is '~playList' too dumb?

**Comment by bkudler** [comment]
'~playerObjects'??

**Comment by catniptwinz** [comment]
I'm thinking ```~playlist```, no camel case, gets at what the object actually is with less ambiguity than anything else we've thought of so far.

**Comment by bkudler** [comment]
yeah, I was going a little camel crazy. ~playlist seems perfect.

**Pull request merged**
