### PR TITLE
Clean up repo

### PR DESCRIPTION
**Pull request by catniptwinz**
This PR removes some duplicate code pasted in error at the bottom of ```forChanna.scd```, removes all ```.DS_Store``` files from the repo, and adds a ```.gitignore``` file.

### CODE REVIEW

**Comment by bkudler** [comment]
ha, was wondering about the duplicate code. I thought it might be good to keep it but have the bottom section illustrate how using different 'pieces' in the set list.

**Comment by catniptwinz** [comment]
No, was just some fat-fingered antics on my part!

**Comment by catniptwinz** [comment]
> but have the bottom section illustrate how using different 'pieces' in the set list

This point is taken, though. I think once the interface feels "done", its use should be illustrated somewhere, whether inline, in the readme, or both.

**Comment by bkudler** [comment]
> No, was just some fat-fingered antics on my part!

no worries!

**Pull request merged**
