### PR TITLE
abstracts setup method

### PR DESCRIPTION
**Pull request by bkudler**

### CODE REVIEW

**Review by catniptwinz — COMMENTED** [review]
So I'm broadly in favor of abstracting setup, but as written this feels a bit obscure in its use of scope. The pseudo-objects (i.e. the namespaces) created during setup (`~pieces`, `~playlist`, `~score`,  `~colorMaker`, and 'player`) have their assignments hidden in setup.scd and end up not being discoverable other than by inspecting currentEnvironment directly.

In general I'd prefer to avoid manipulating the state of currentEnvironment inside included files like this. If setup didn't need to be a Routine (i.e. a forked Function), I'd suggest that it might return some data structure containing pieces, player, etc instead. Off the top of my head, the only other way I can think of to do it is to implement everything with compiled classes (instance of Channa contains instance of ChannaPlayer etc). I can mock that up in a branch if you're curious about what it would look like, but I don't think it's really your thing, and anyway I'm very much open to other ideas!

**Comment by bkudler** [comment]
> So I'm broadly in favor of abstracting setup, but as written this feels a bit obscure in its use of scope. The pseudo-objects (i.e. the namespaces) created during setup (`~pieces`, `~playlist`, `~score`, `~colorMaker`, and 'player`) have their assignments hidden in setup.scd and end up not being discoverable other than by inspecting currentEnvironment directly.
> 
> In general I'd prefer to avoid manipulating the state of currentEnvironment inside included files like this. If setup didn't need to be a Routine (i.e. a forked Function), I'd suggest that it might return some data structure containing pieces, player, etc instead. Off the top of my head, the only other way I can think of to do it is to implement everything with compiled classes (instance of Channa contains instance of ChannaPlayer etc). I can mock that up in a branch if you're curious about what it would look like, but I don't think it's really your thing, and anyway I'm very much open to other ideas!

yeah, I realized the updating `currentEnviornment` was a little sloppy, but didn't see a good way around it and also sort of figured, well, that's what that thing is there for. I thought about it a little more and thought... well maybe not quite, that made me want to get rid of it all together. I came up with this solution, which involves only adding/modifying one variable on `currentEnviornment`. I also like this because it makes it easier to use different set up files. For instance, one could have multiple set up files with multiple of these "realization" objects, each using a different set up file and thus using different players and models... we are a long way off from wanting to do that, but it seems helpful to move in that direction. Let me know what you think.

**Comment by catniptwinz** [comment]
Getting rid of the fork raises the question of whether this program should take responsibility for the state of the Server or whether that's up to the user.

Notice that with this version, "Config OK" prints before the Server has booted. Not that that's necessarily a dealbreaker, but it jumped out at me because the forked setup Function thing is a pattern I use for live sets, where I want to be able to eval one block that will work consistently ideally regardless of the state of the client and Server and watch stdout to see whether all my infrastructure is good to go.

That may or may not be your goal here, but either way we probably need to decide how we handle configuring and booting the Server. We're kind of stuck between two approaches now, with some ServerOptions stuff factored out to `setup.scd` which will have no effect on a running Server (which if we're *really* looking to abstract this might not even necessarily be bound to 's') unless it's rebooted and vestigial calls to `Server.bootSync` and `Function.forkIfNeeded` in the piece init methods (my fault).

(As an aside, I think the scheduling/blocking mechanism of SC is one of its foundational constraints. So much of it is built on Routines, which return their own time deltas, so in a fundamental sense, "musical work" is ultimately gonna get done via side effects, and so is anything client-side that depends on the state of the Server. Just a question of localizing those side effects in a sane/predictable way.)

Anyway, do you envision this being something totally hardened in which the user evals a single statement that builds everything out regardless of prior state or something more minimal in which it'd be on them to have the server running, adequate memSize, etc?

**Comment by bkudler** [comment]
> Getting rid of the fork raises the question of whether this program should take responsibility for the state of the Server or whether that's up to the user.
> 
> Notice that with this version, "Config OK" prints before the Server has booted. Not that that's necessarily a dealbreaker, but it jumped out at me because the forked setup Function thing is a pattern I use for live sets, where I want to be able to eval one block that will work consistently ideally regardless of the state of the client and Server and watch stdout to see whether all my infrastructure is good to go.
> 
> That may or may not be your goal here, but either way we probably need to decide how we handle configuring and booting the Server. We're kind of stuck between two approaches now, with some ServerOptions stuff factored out to `setup.scd` which will have no effect on a running Server (which if we're _really_ looking to abstract this might not even necessarily be bound to 's') unless it's rebooted and vestigial calls to `Server.bootSync` and `Function.forkIfNeeded` in the piece init methods (my fault).
> 


okay, so here is, I think, a decent solution. I kind of think the piece should be a stand alone music-box type of thing. User chooses their pieces starts things up and it plays for them. They can set their server options, but that's kind of it as far as the final-end user (there's a different kind user/developer who adds in their own pieces). The stand-alone nature of this thing lead me to just reboot the server every time and to forcing everything to run on the local server, 's'. 

 I understand my way of making sure that server is running and good before doing the configuration is kind of hack-y, but I feel cool with it because, first, it allows server set up and infrastructure setup to work in one block, while splitting responsibility of each of these to individual methods (which I feel is more readable) and, secondly, it doesn't just use arbitrary wait times, it actually checks against the local server, which, as stated before, is the server this thing _has_ to run on.

I can see the problems and, at this point, I'm not convinced this is _that_ much cleaner than the original setup thing all in one block with a fork and living in `forChanna.scd`. 

We could also just have the original `.fork` block with server config inside etc.. in a file not as part of an event and then just load that file in forChanna.scd`. 

Do you think this pr mostly fine? Do you think there's a way you could improve on this? Do you think the way stated right above is better? Or do you think we should just go back to what we had?

**Comment by catniptwinz** [comment]
Hey, sorry this took me a few days to get back to! A few things to touch on.

First, unless I misunderstand what you're going for, I don't see an advantage to checking the Server in a while loop vs using Condition or even better, using the existing methods of Server (`sync`, `bootSync`, `waitForBoot`, `doWhenBooted`, etc) that are designed for this purpose.

Beyond that, I think that for now the master branch is clearer -- all includes, all globals, and all config stay at the top level, the setup func tells you exactly what it does, etc. Not to get too bureaucratic about this but maybe there would be some advantage to opening issues so we have a record of where things are heading?

Speaking of where we're heading, I like the idea that this is a "music box" that can "just" play the composition, but can also be hacked on and extended if you understand the interface. That helps me understand how we should be handling the Server. I'd like to propose that:

- We assume that the Server is not booted when setup is eval'd. (We can always tackle this later if we want to.)
- The setup routine explicitly boots the Server after building out all the other infrastructure.
- "Config OK" should mean that all includes etc have been evaluated without errors and the Server has finished booting.
- Pieces can modify Server options in their init methods (init presumes no server running). That means if you write a piece that needs e.g. a larger memSize, you can account for that in its init method.
- Pieces can take actions that presume a running server in setup/teardown and everything in between. Any Routine-specific stuff (etc yield/wait) in piece methods should be wrapped in `{}.forkIfNeeded` so those methods can be called outside of a player for development/testing.

I have a local branch that addresses all of this which I'll push in a moment so you can have a look at it and let me know if it's something you think we can/should build on.

Ultimately I do see a case for abstracting setup and making it possible to have multiple realizations and I think we can get it done. We also have some rough edges that keep sticking out at me, like it's really awkward to have to keep changing `~libPath` back and forth (the story behind the non-availability of `Document` in scvim is long and depressing). On one hand we could abstract setup out to e.g. `lib/helpers/realization.scd` and call `~realization.create(~libPath)`. On the other hand, we could write a Class for realization and call `Channa.new(path)` or whatever.

**Comment by catniptwinz** [comment]
Just pushed branch explicit-setup ( #8 ). I think if we can settle on ground rules regarding the Server, this could be a basis for continuing with abstracting setup and the next step would be thinking through the pros/cons of .scd includes vs classfiles/quarks.

**Comment by bkudler** [comment]
> Hey, sorry this took me a few days to get back to! A few things to touch on.
> 

 No problem, sorry , it took me a minute to respond. 


> First, unless I misunderstand what you're going for, I don't see an advantage to checking the Server in a while loop vs using Condition or even better, using the existing methods of Server (`sync`, `bootSync`, `waitForBoot`, `doWhenBooted`, etc) that are designed for this purpose.
> 

I thought about using Condition, it maybe is helpful, but the while loop just seems more readable, not using some native to SC... that one is more open for debate, but ultimately not that important. I tried using the built in Server functions, but all of them would fire when the server was booting, not running, and, thus "config okay!" wouldn't be the last thing to print and stuff would get added before it printed. Do you know if all those Server methods that have 'boot' in the name run once the server starts to boot or once it has changed from booting to running? 

> Beyond that, I think that for now the master branch is clearer -- all includes, all globals, and all config stay at the top level, the setup func tells you exactly what it does, etc. Not to get too bureaucratic about this but maybe there would be some advantage to opening issues so we have a record of where things are heading?
> 

I'm not so happy about the currentEnviornment usage, but I can definitely live with it for now. Issues would be helpful in this case. I think most of the time PRs will be appropriate but something like "too much use of currentEnviornment" could be an issue. Just to reiterate, actual code is probably more helpful than issues at this point.

> Speaking of where we're heading, I like the idea that this is a "music box" that can "just" play the composition, but can also be hacked on and extended if you understand the interface. That helps me understand how we should be handling the Server. I'd like to propose that:
> 
> * We assume that the Server is not booted when setup is eval'd. (We can always tackle this later if we want to.)

This is my one issue. I think we should just reboot the server, it's easy as booting it, and if the server _isn't_ running, it will work the same way. 

> * Pieces can take actions that presume a running server in setup/teardown and everything in between. Any Routine-specific stuff (etc yield/wait) in piece methods should be wrapped in `{}.forkIfNeeded` so those methods can be called outside of a player for development/testing.
> 

That seems like a developer by developer choice, but we can put that in the README as best practice and then we can both make sure that any code in this repo follows that standard.

> Ultimately I do see a case for abstracting setup and making it possible to have multiple realizations and I think we can get it done. We also have some rough edges that keep sticking out at me, like it's really awkward to have to keep changing `~libPath` back and forth (the story behind the non-availability of `Document` in scvim is long and depressing). On one hand we could abstract setup out to e.g. `lib/helpers/realization.scd` and call `~realization.create(~libPath)`. On the other hand, we could write a Class for realization and call `Channa.new(path)` or whatever.

this seems like something worthy of an issue. Suggest these possible solutions in the issue and we can discuss there.

**Comment by catniptwinz** [comment]
> Do you know if all those Server methods that have 'boot' in the name run once the server starts to boot or once it has changed from booting to running?

> I'm not so happy about the currentEnviornment usage, but I can definitely live with it for now.

Same here. My thinking is just that what we're doing in the setup routine is basically mocking up an init method out in the open while we decide how the class or pseudoclass should be implemented. While we sort that out I think it makes sense to keep all the state of that class/pseudoclass in one place, right in front of our faces.

> This is my one issue. I think we should just reboot the server, it's easy as booting it, and if the server isn't running, it will work the same way.

Sure, fair enough. See my response in #8 for some example implementations.

> That seems like a developer by developer choice, but we can put that in the README as best practice and then we can both make sure that any code in this repo follows that standard.

Yes, totally agreed.

> this seems like something worthy of an issue. Suggest these possible solutions in the issue and we can discuss there.

Will try to get to this soon. I think the ugliness of `~libPath` is sort of our "canary" issue that may ultimately point to how we want to structure setup and realizations.

**Comment by bkudler** [comment]
> > I'm not so happy about the currentEnviornment usage, but I can definitely live with it for now.
> 
> Same here. My thinking is just that what we're doing in the setup routine is basically mocking up an init method out in the open while we decide how the class or pseudoclass should be implemented. While we sort that out I think it makes sense to keep all the state of that class/pseudoclass in one place, right in front of our faces.
> 

yeah, agreed. I'll close this PR.

> Will try to get to this soon. I think the ugliness of `~libPath` is sort of our "canary" issue that may ultimately point to how we want to structure setup and realizations.

I have an idea on how to handle this. I'll have a PR with some stuff this weekend.



> > Do you know if all those Server methods that have 'boot' in the name run once the server starts to boot or once it has changed from booting to running?
> 

do you know by chance?

**Comment by catniptwinz** [comment]
> 
> 
>         Do you know if all those Server methods that have 'boot' in the name run once the server starts to boot or once it has changed from booting to running?
> 
> do you know by chance?

Yeah, I just had a quick look at the implementations of Server.waitForBoot, Server.doWhenBooted, and Server.bootSync for the first time in a while, and the takeaways for me are:

- All three methods ultimately call Server.doWhenBooted with slight variations in terms of how they get there (doWhenBooted is actually implemented in class ServerStatusWatcher).
- The onComplete Function is always evaluated in a Routine.
- The Server is always sync'd directly prior to onComplete being eval'd. 
- The property that's being tested for is serverRunning. ServerStatusWatcher checks it every 0.2 seconds in a while loop.

Here's the actual code that runs under the hood:

https://github.com/supercollider/supercollider/blob/2b6e6d01be1b56501661373b5381b58fc3ba2f3a/SCClassLibrary/Common/Control/ServerStatus.sc#L51-L85

**Comment by bkudler** [comment]
> > ```
> >     Do you know if all those Server methods that have 'boot' in the name run once the server starts to boot or once it has changed from booting to running?
> > ```
> > 
> > 
> > do you know by chance?
> 
> Yeah, I just had a quick look at the implementations of Server.waitForBoot, Server.doWhenBooted, and Server.bootSync for the first time in a while, and the takeaways for me are:
> 
> * All three methods ultimately call Server.doWhenBooted with slight variations in terms of how they get there (doWhenBooted is actually implemented in class ServerStatusWatcher).
> * The onComplete Function is always evaluated in a Routine.
> * The Server is always sync'd directly prior to onComplete being eval'd.
> * The property that's being tested for is serverRunning. ServerStatusWatcher checks it every 0.2 seconds in a while loop.
> 
> Here's the actual code that runs under the hood:
> 
> https://github.com/supercollider/supercollider/blob/2b6e6d01be1b56501661373b5381b58fc3ba2f3a/SCClassLibrary/Common/Control/ServerStatus.sc#L51-L85

ah, thanks! I should get more used to looking in the source code! After some investigating it seems like all that has to be done to say the server is running is that it has started booting, the client has been notified this is happening and hasn't failed yet... doesn't seem like there's any good way to be like, I want the server to be DONE booting without seem weird check from the end developer.. huh, good to know!

**Pull request closed without merging**
